# Generated by Django 5.1.6 on 2026-09-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0002_lead_email_lead_facebook_url_lead_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='media_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='media_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
